export const TRANSLATIONS = {
  ko: {
    search: "검색", fav: "찜", theme_blue: "네이비 테마", theme_dark: "다크 테마", theme_light: "화이트 테마", theme_sunset: "선셋 (Sunset)", theme_glass: "리퀴드 글래스",
    cols: "가로:", rows: "세로:", total: "총:", slots: "칸", settings: "설정", synced: "동기화됨", login: "로그인", save_store: "세팅 저장소",
    empty_status: "비어있음", slot: "슬롯", select_fav: "⭐ 찜 목록에서 선택", search_new: "새 코인 검색",
    loading: "데이터 로드 중...", fetch_failed: "데이터 수급 실패 (재시도 중...)",
    pro_slot: "PRO 전용 슬롯", pro_desc: "월 990원에 잠금을 해제하고\n무제한 차트를 경험하세요.",
    theme_sel: "테마 선택", lang_sel: "언어 설정", confirm: "확인", dev_downgrade: "[개발자용] 무료 등급으로 강제 돌아가기",
    cloud_title: "클라우드 연동", cloud_desc: "구글이나 애플 계정으로 로그인하여 나만의 차트 세팅과 찜 목록을 안전하게 저장하고 언제든 다른 기기에서 불러오세요.",
    cloud_on: "현재 모든 셋팅이 클라우드에 실시간으로 안전하게 자동 저장되고 있습니다.", logout: "로그아웃 (동기화 해제)",
    login_google: "Google 계정으로 계속하기", login_apple: "Apple ID로 계속하기",
    save_title: "차트 세팅 저장소", save_desc: "다양한 화면 분할, 테마, 코인 목록 구성을 슬롯별로 저장해두고 한 번에 불러올 수 있습니다. (이름 변경 가능)",
    empty: "비어있음", overwrite: "현재화면 덮어쓰기", save_here: "여기에 저장", load: "불러오기",
    add_coin: "코인 추가", ex_btc: "예: BTC", show_chart: "차트 띄우기", save_fav_btn: "찜 목록 저장",
    my_favs: "나의 찜 목록", no_favs: "찜한 코인이 없습니다.",
    paywall_desc: "단돈 990원으로 최고의 트레이딩 환경을 완성하세요.",
    paywall_f1: "무제한 차트 화면 분할 (최대 20개 동시 모니터링)", paywall_f2: "클라우드 동기화 및 커스텀 세팅 5개 멀티 저장", paywall_f3: "모든 프리미엄 전용 테마 무제한 사용 가능",
    paywall_btn: "₩990 / 월 결제하기",
    int_1: "1분", int_5: "5분", int_15: "15분", int_60: "1시간", int_240: "4시간", int_D: "일봉", int_W: "주봉",
    drag_resize: "드래그하여 우측 숫자 칸 너비 조절", hide_menu: "상단 메뉴 숨기기", show_menu: "상단 메뉴 펼치기",
    toast_load_success: "클라우드에서 기존 설정을 성공적으로 불러왔습니다! ☁️",
    toast_new_cloud: "클라우드 연동이 완료되었습니다! 설정이 로드됩니다. ☁️",
    toast_sync_local: "클라우드 동기화가 로컬 모드로 활성화되었습니다.",
    toast_login_fail: "로그인에 실패했습니다.",
    toast_upgrade_success: "MVT PRO 구독이 완료되었습니다! 무제한 기능을 즐겨보세요 🚀",
    toast_save_slot: "{name}에 현재 화면이 저장되었습니다! 💾",
    toast_load_slot: "{name} 세팅을 불러왔습니다! 🚀",
    toast_unsync: "클라우드 동기화가 해제되었습니다.",
    toast_downgrade: "무료 등급으로 전환되었습니다. 결제창을 다시 확인해 보세요!",
    indicators: "지표 설정", volume: "거래량 (Volume)", ma_lines: "이동평균선 (MA)", add: "추가", bb_lines: "볼린저밴드 (BB)",
    draw_btn: "선 긋기", draw_trend: "대각선", draw_horiz: "가로선", draw_vert: "세로선", thickness: "두께", clear_all: "모두 지우기", undo: "실행 취소",
    alarm_toast: "🚨 {symbol} 가격이 {price}에 도달했습니다!", alarm_title: "가격 알림"
  },
  en: {
    search: "Search", fav: "Fav", theme_blue: "Navy Theme", theme_dark: "Dark Theme", theme_light: "Light Theme", theme_sunset: "Sunset Theme", theme_glass: "Liquid Glass",
    cols: "Cols:", rows: "Rows:", total: "Total:", slots: "", settings: "Settings", synced: "Synced", login: "Login", save_store: "Saved Sets",
    empty_status: "Empty", slot: "Slot", select_fav: "⭐ Select from Favorites", search_new: "Search New Coin",
    loading: "Loading data...", fetch_failed: "Fetch failed (Retrying...)",
    pro_slot: "PRO Slot", pro_desc: "Unlock for $0.99/month\nand experience unlimited charts.",
    theme_sel: "Select Theme", lang_sel: "Language", confirm: "Confirm", dev_downgrade: "[Dev] Force Downgrade to Free",
    cloud_title: "Cloud Sync", cloud_desc: "Login with Google or Apple to safely save your chart settings and favorites to the cloud.",
    cloud_on: "All settings are currently being safely auto-saved to the cloud in real-time.", logout: "Logout (Unsync)",
    login_google: "Continue with Google", login_apple: "Continue with Apple",
    save_title: "Chart Settings Saves", save_desc: "Save various layouts, themes, and coin lists in slots and load them anytime. (Renameable)",
    empty: "Empty", overwrite: "Overwrite Current", save_here: "Save Here", load: "Load",
    add_coin: "Add Coin", ex_btc: "Ex: BTC", show_chart: "Show Chart", save_fav_btn: "Save to Favorites",
    my_favs: "My Favorites", no_favs: "No favorite coins.",
    paywall_desc: "Complete the best trading environment for just $0.99.",
    paywall_f1: "Unlimited chart splits (Monitor up to 20 simultaneously)", paywall_f2: "Cloud sync & 5 custom multi-save slots", paywall_f3: "Unlimited use of all premium exclusive themes",
    paywall_btn: "Pay $0.99 / Month",
    int_1: "1m", int_5: "5m", int_15: "15m", int_60: "1H", int_240: "4H", int_D: "1D", int_W: "1W",
    drag_resize: "Drag to resize right price scale", hide_menu: "Hide top menu", show_menu: "Show top menu",
    toast_load_success: "Successfully loaded settings from cloud! ☁️",
    toast_new_cloud: "Cloud sync complete! Settings loaded. ☁️",
    toast_sync_local: "Cloud sync activated in local mode.",
    toast_login_fail: "Login failed.",
    toast_upgrade_success: "MVT PRO subscription complete! Enjoy unlimited features 🚀",
    toast_save_slot: "Current screen saved to {name}! 💾",
    toast_load_slot: "Loaded {name} settings! 🚀",
    toast_unsync: "Cloud sync disabled.",
    toast_downgrade: "Downgraded to free tier. Check the paywall again!",
    indicators: "Indicators", volume: "Volume", ma_lines: "Moving Averages", add: "Add", bb_lines: "Bollinger Bands",
    draw_btn: "Draw", draw_trend: "Trend", draw_horiz: "Horizontal", draw_vert: "Vertical", thickness: "Width", clear_all: "Clear All", undo: "Undo",
    alarm_toast: "🚨 {symbol} price reached {price}!", alarm_title: "Price Alert"
  },
  zh: {
    search: "搜索", fav: "收藏", theme_blue: "海军蓝主题", theme_dark: "暗黑主题", theme_light: "明亮主题", theme_sunset: "日落主题", theme_glass: "液态玻璃",
    cols: "列:", rows: "行:", total: "总计:", slots: "个", settings: "设置", synced: "已同步", login: "登录", save_store: "保存的设置",
    empty_status: "空", slot: "插槽", select_fav: "⭐ 从收藏夹选择", search_new: "搜索新币种",
    loading: "数据加载中...", fetch_failed: "获取失败 (重试中...)",
    pro_slot: "PRO 专属插槽", pro_desc: "每月仅需 ¥5.50 解锁\n体验无限制图表。",
    theme_sel: "选择主题", lang_sel: "语言设置", confirm: "确认", dev_downgrade: "[开发者] 强制降级为免费版",
    cloud_title: "云同步", cloud_desc: "使用 Google 或 Apple 帐号登录，安全保存您的图表设置和收藏夹到云端。",
    cloud_on: "所有设置目前正安全地实时自动保存到云端。", logout: "登出 (取消同步)",
    login_google: "使用 Google 继续", login_apple: "使用 Apple 继续",
    save_title: "图表设置保存", save_desc: "将各种布局、主题和币种列表保存在插槽中，随时加载。(可重命名)",
    empty: "空", overwrite: "覆盖当前", save_here: "保存到此处", load: "加载",
    add_coin: "添加币种", ex_btc: "例: BTC", show_chart: "显示图表", save_fav_btn: "保存到收藏夹",
    my_favs: "我的收藏", no_favs: "没有收藏的币种。",
    paywall_desc: "仅需 ¥5.50 即可打造最佳交易环境。",
    paywall_f1: "无限制图表分屏 (最多同时监控 20 个)", paywall_f2: "云同步及 5 个自定义多重保存插槽", paywall_f3: "无限制使用所有高级专属主题",
    paywall_btn: "支付 ¥5.50 / 月",
    int_1: "1分", int_5: "5分", int_15: "15分", int_60: "1小时", int_240: "4小时", int_D: "日线", int_W: "周线",
    drag_resize: "拖动以调整右侧价格刻度宽度", hide_menu: "隐藏顶部菜单", show_menu: "显示顶部菜单",
    toast_load_success: "成功从云端加载设置！ ☁️",
    toast_new_cloud: "云同步完成！设置已加载。 ☁️",
    toast_sync_local: "云同步已在本地模式下激活。",
    toast_login_fail: "登录失败。",
    toast_upgrade_success: "MVT PRO 订阅完成！尽情享受无限制功能 🚀",
    toast_save_slot: "当前屏幕已保存至 {name}！ 💾",
    toast_load_slot: "已加载 {name} 设置！ 🚀",
    toast_unsync: "云同步已禁用。",
    toast_downgrade: "已降级为免费版。请再次查看支付页面！",
    indicators: "指标设置", volume: "成交量 (Volume)", ma_lines: "移动平均线 (MA)", add: "添加", bb_lines: "布林带 (BB)",
    draw_btn: "画线", draw_trend: "趋势线", draw_horiz: "水平线", draw_vert: "垂直线", thickness: "宽度", clear_all: "全部清除", undo: "撤销",
    alarm_toast: "🚨 {symbol} 价格已达到 {price}！", alarm_title: "价格提醒"
  },
  ru: {
    search: "Поиск", fav: "Избр.", theme_blue: "Темно-синяя тема", theme_dark: "Темная тема", theme_light: "Светлая тема", theme_sunset: "Тема Закат", theme_glass: "Жидкое стекло",
    cols: "Кол:", rows: "Стр:", total: "Всего:", slots: "", settings: "Настройки", synced: "Синхр.", login: "Войти", save_store: "Сохраненные",
    empty_status: "Пусто", slot: "Слот", select_fav: "⭐ Выбрать из избранного", search_new: "Поиск новой монеты",
    loading: "Загрузка данных...", fetch_failed: "Ошибка загрузки (Повтор...)",
    pro_slot: "PRO Слот", pro_desc: "Разблокируйте за 69 ₽/мес\nи получите неограниченные графики.",
    theme_sel: "Выбор темы", lang_sel: "Язык", confirm: "Подтвердить", dev_downgrade: "[Dev] Принудительно понизить до Free",
    cloud_title: "Облачная синхронизация", cloud_desc: "Войдите с помощью Google или Apple, чтобы безопасно сохранять настройки графиков и избранное в облаке.",
    cloud_on: "Все настройки в настоящее время безопасно автоматически сохраняются в облаке в реальном времени.", logout: "Выйти (Отключить синхр.)",
    login_google: "Продолжить с Google", login_apple: "Продолжить с Apple",
    save_title: "Сохранения настроек графиков", save_desc: "Сохраняйте различные макеты, темы и списки монет в слоты и загружайте их в любое время. (Можно переименовать)",
    empty: "Пусто", overwrite: "Перезаписать текущий", save_here: "Сохранить здесь", load: "Загрузить",
    add_coin: "Добавить монету", ex_btc: "Напр: BTC", show_chart: "Показать график", save_fav_btn: "Сохранить в избранное",
    my_favs: "Мое избранное", no_favs: "Нет избранных монет.",
    paywall_desc: "Создайте лучшую торговую среду всего за 69 ₽.",
    paywall_f1: "Неограниченное разделение графиков (До 20 одновременно)", paywall_f2: "Облачная синхронизация и 5 слотов для сохранения", paywall_f3: "Неограниченное использование всех премиум тем",
    paywall_btn: "Оплатить 69 ₽ / Месяц",
    int_1: "1м", int_5: "5м", int_15: "15м", int_60: "1Ч", int_240: "4Ч", int_D: "1Д", int_W: "1Н",
    drag_resize: "Потяните для изменения ширины шкалы цен", hide_menu: "Скрыть верхнее меню", show_menu: "Показать верхнее меню",
    toast_load_success: "Настройки успешно загружены из облака! ☁️",
    toast_new_cloud: "Синхронизация с облаком завершена! Настройки загружены. ☁️",
    toast_sync_local: "Облачная синхронизация активирована в локальном режиме.",
    toast_login_fail: "Ошибка входа.",
    toast_upgrade_success: "Подписка MVT PRO оформлена! Наслаждайтесь неограниченными функциями 🚀",
    toast_save_slot: "Текущий экран сохранен в {name}! 💾",
    toast_load_slot: "Загружены настройки {name}! 🚀",
    toast_unsync: "Облачная синхронизация отключена.",
    toast_downgrade: "Понижено до бесплатного уровня. Проверьте окно оплаты снова!",
    indicators: "Индикаторы", volume: "Объем (Volume)", ma_lines: "Скользящие средние (MA)", add: "Добавить", bb_lines: "Полосы Боллинджера (BB)",
    draw_btn: "Рисовать", draw_trend: "Тренд", draw_horiz: "Горизонт.", draw_vert: "Вертик.", thickness: "Толщина", clear_all: "Очистить все", undo: "Отменить",
    alarm_toast: "🚨 Цена {symbol} достигла {price}!", alarm_title: "Оповещение о цене"
  }
};

export const EXCHANGES = [
  { id: 'UPBIT', name: '업비트 (Upbit)', defaultQuote: 'KRW' },
  { id: 'BITHUMB', name: '빗썸 (Bithumb)', defaultQuote: 'KRW' },
  { id: 'BINANCE', name: '바이낸스 (Binance)', defaultQuote: 'USDT' },
  { id: 'OKX', name: 'OKX', defaultQuote: 'USDT' },
  { id: 'BYBIT', name: '바이비트 (Bybit)', defaultQuote: 'USDT' },
];

export const INTERVALS = [
  { value: '1', upbit: 'minutes/1', binance: '1m', okx: '1m', bybit: '1', bithumb: '1m' },
  { value: '5', upbit: 'minutes/5', binance: '5m', okx: '5m', bybit: '5', bithumb: '5m' },
  { value: '15', upbit: 'minutes/15', binance: '15m', okx: '15m', bybit: '15', bithumb: '10m' }, 
  { value: '60', upbit: 'minutes/60', binance: '1h', okx: '1H', bybit: '60', bithumb: '1h' },
  { value: '240', upbit: 'minutes/240', binance: '4h', okx: '4H', bybit: '240', bithumb: '6h' }, 
  { value: 'D', upbit: 'days', binance: '1d', okx: '1D', bybit: 'D', bithumb: '24h' },
  { value: 'W', upbit: 'weeks', binance: '1w', okx: '1W', bybit: 'W', bithumb: '24h' },
];

export const PRESET_COLORS = ['#ffffff', '#ef4444', '#facc15', '#4ade80', '#38bdf8', '#a855f7'];
